version: '3'

services:
  event-producer:
    build:
      context: ./cmd/event-producer
    container_name: event-producer
    ports:
      - "4000:4000"
    depends_on:
      - kafka_broker

  event-consumer:
    build:
      context: ./cmd/event-consumer
    container_name: event-consumer
    ports:
      - "3001:3001"
    depends_on:
      - kafka_broker
      - cassandra

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka_broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka_broker
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka_broker:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092,PLAINTEXT_INTERNAL://kafka_broker:9092,PLAINTEXT_OUTSIDE://localhost:9094
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092,PLAINTEXT_INTERNAL://kafka_broker:29092,PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ./local/data/db/cassandra:/var/lib/cassandra

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file:
      - ./config/influxdb/influxdb.env
    ports:
      - "8086:8086"
    volumes:
      - ./local/data/db/influxdb:/var/lib/influxdb2:rw

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    env_file:
      - ./config/influxdb/influxdb.env
    volumes:
      - ./config/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
